# Generated by Django 5.1.2 on 2024-10-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('MANAGER', 'Manager'), ('COMMON', 'Common')], default='COMMON', max_length=10),
        ),
    ]
